server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # Never cache index.html so browser always gets latest chunk filenames
  location = /index.html {
    add_header Cache-Control "no-store, no-cache, must-revalidate";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
